trigger:
  branches:
    include:
      - dev
      - qa
      - uat
      - staging
      - prod

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: 'b64a138d-2774-492c-9363-ff85e9f882db'
  imageRepository: 'orders-microservice'
  containerRegistry: 'muriloecommerceregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/OrderMicroservice.API/Dockerfile'
  tag: '$(Build.BuildId)'
  linuxImageName: 'ubuntu-latest'
  windowsImageName: 'windows-latest'
  aksClusterName: 'ecommerce-aks-cluster'
  devAksServiceConnectionName: 'dev-ecommerce-aks-cluster-dev-1752351360344'
  qaAksServiceConnectionName: 'qa-ecommerce-aks-cluster-qa-1752351543761'
  uatAksServiceConnectionName: 'uat-ecommerce-aks-cluster-uat-1752351669265'
  stagingAksServiceConnectionName: 'staging-ecommerce-aks-cluster-staging-1752351722062'
  prodAksServiceConnectionName: 'prod-ecommerce-aks-cluster-prod-1752351785091'
  devKubernetesNamespace: 'dev'
  qaKubernetesNamespace: 'qa'
  uatKubernetesNamespace: 'uat'
  stagingKubernetesNamespace: 'staging'
  prodKubernetesNamespace: 'prod'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(linuxImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              buildContext: $(Build.SourcesDirectory)
              tags: |
                $(tag)
  - stage: Test
    displayName: Test and publish result stage
    jobs:
      - job: RunTest
        displayName: Run unit tests
        pool:
          vmImage: $(windowsImageName)
        steps:
          - checkout: self
            displayName: Checkout source code
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.0.300'
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Restore packages
            inputs:
              command: 'restore'
              projects: '**/*.sln'
          - task: DotNetCoreCLI@2
            displayName: Build solution
            inputs:
              command: 'build'
              projects: '**/*.sln'
              arguments: '--configuration Release'
          - task: DotNetCoreCLI@2
            displayName: Run tests
            inputs:
              command: 'test'
              projects: '**/*Tests.csproj'
              arguments: '--configuration Release --collect:"Code Coverage"'
  - stage: DeployToDev
    displayName: Deploy to Dev
    dependsOn: Test
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    variables:
      - group: orders-microservice-dev
    jobs:
      - deployment: DeploymentToDev
        displayName: Deployment to Dev Environment
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout source code
                - script: |
                    echo "Listing contents of k8s"
                    ls -l $(Build.SourcesDirectory)/k8s/dev
                  displayName: 'List Files in k8s/dev Directory'
                - script: |
                    find $(Build.SourcesDirectory)/k8s/dev -type f \( -name "*.yaml" -o -name "*.yml" \) -exec sed -i 's/__TAG__/$(tag)/g' {} +
                  displayName: 'Replace image tag in all deployment files'
                - task: Kubernetes@1
                  displayName: Deploy to dev namespace in kubernetes
                  inputs:
                    kubernetesServiceEndpoint: $(devAksServiceConnectionName)
                    kubernetesCluster: $(aksClusterName)
                    namespace: $(kubernetesNamespace)
                    command: apply
                    arguments: '-f $(Build.SourcesDirectory)/k8s/dev/.'
  - stage: DeployToQA
    displayName: Deploy to QA
    dependsOn: Test
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/qa'))
    variables:
      - group: orders-microservice-qa
    jobs:
      - deployment: DeploymentToQA
        displayName: Deployment to QA Environment
        environment: qa
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout source code
                - script: |
                    echo "Listing contents of k8s"
                    ls -l $(Build.SourcesDirectory)/k8s/qa
                  displayName: 'List Files in k8s/qa Directory'
                - script: |
                    find $(Build.SourcesDirectory)/k8s/qa -type f \( -name "*.yaml" -o -name "*.yml" \) -exec sed -i 's/__TAG__/$(tag)/g' {} +
                  displayName: 'Replace image tag in all deployment files'
                - task: Kubernetes@1
                  displayName: Deploy to qa namespace in kubernetes
                  inputs:
                    kubernetesServiceEndpoint: $(qaAksServiceConnectionName)
                    kubernetesCluster: $(aksClusterName)
                    namespace: $(kubernetesNamespace)
                    command: apply
                    arguments: '-f $(Build.SourcesDirectory)/k8s/qa/.'
  - stage: DeployToUAT
    displayName: Deploy to UAT
    dependsOn: Test
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/uat'))
    variables:
      - group: orders-microservice-uat
    jobs:
      - deployment: DeploymentToUAT
        displayName: Deployment to UAT Environment
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout source code
                - script: |
                    echo "Listing contents of k8s"
                    ls -l $(Build.SourcesDirectory)/k8s/uat
                  displayName: 'List Files in k8s/uat Directory'
                - script: |
                    find $(Build.SourcesDirectory)/k8s/uat -type f \( -name "*.yaml" -o -name "*.yml" \) -exec sed -i 's/__TAG__/$(tag)/g' {} +
                  displayName: 'Replace image tag in all deployment files'
                - task: Kubernetes@1
                  displayName: Deploy to uat namespace in kubernetes
                  inputs:
                    kubernetesServiceEndpoint: $(uatAksServiceConnectionName)
                    kubernetesCluster: $(aksClusterName)
                    namespace: $(kubernetesNamespace)
                    command: apply
                    arguments: '-f $(Build.SourcesDirectory)/k8s/uat/.'
  - stage: DeployToStaging
    displayName: Deploy to Staging
    dependsOn: Test
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
    variables:
      - group: orders-microservice-staging
    jobs:
      - deployment: DeploymentToStaging
        displayName: Deployment to Staging Environment
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout source code
                - script: |
                    echo "Listing contents of k8s"
                    ls -l $(Build.SourcesDirectory)/k8s/staging
                  displayName: 'List Files in k8s/staging Directory'
                - script: |
                    find $(Build.SourcesDirectory)/k8s/staging -type f \( -name "*.yaml" -o -name "*.yml" \) -exec sed -i 's/__TAG__/$(tag)/g' {} +
                  displayName: 'Replace image tag in all deployment files'
                - task: Kubernetes@1
                  displayName: Deploy to staging namespace in kubernetes
                  inputs:
                    kubernetesServiceEndpoint: $(stagingAksServiceConnectionName)
                    kubernetesCluster: $(aksClusterName)
                    namespace: $(kubernetesNamespace)
                    command: apply
                    arguments: '-f $(Build.SourcesDirectory)/k8s/staging/.'
  - stage: DeployToProduction
    displayName: Deploy to Production
    dependsOn: Test
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/prod'))
    variables:
      - group: orders-microservice-prod
    jobs:
      - deployment: DeploymentToProduction
        displayName: Deployment to Production Environment
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout source code
                - script: |
                    echo "Listing contents of k8s"
                    ls -l $(Build.SourcesDirectory)/k8s/prod
                  displayName: 'List Files in k8s/prod Directory'
                - script: |
                    find $(Build.SourcesDirectory)/k8s/prod -type f \( -name "*.yaml" -o -name "*.yml" \) -exec sed -i 's/__TAG__/$(tag)/g' {} +
                  displayName: 'Replace image tag in all deployment files'
                - task: Kubernetes@1
                  displayName: Deploy to prod namespace in kubernetes
                  inputs:
                    kubernetesServiceEndpoint: $(prodAksServiceConnectionName)
                    kubernetesCluster: $(aksClusterName)
                    namespace: $(kubernetesNamespace)
                    command: apply
                    arguments: '-f $(Build.SourcesDirectory)/k8s/prod/.'
                    